version: '2'

services:
  influxdb:
    image: influxdb:0.13
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: 'true'
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - '8083:8083'
      - '8086:8086'
    # restart: always
    # expose:
    #   - '8090'
    #   - '8099'

  grafana:
    image: grafana/grafana:3.1.1
    links:
      - influxdb
    volumes:
      - ./grafana-data:/var/lib/grafana
    environment:
      INFLUXDB_HOST: 'influxdb'
      INFLUXDB_NAME: 'tfws'
      INFLUXDB_IS_GRAFANADB: 'true'
      GF_SECURITY_ADMIN_USER: '${GF_ADMIN_USER}'
      GF_SECURITY_ADMIN_PASSWORD: '${GF_ADMIN_PASSWORD}'
      GF_USERS_ALLOW_SIGN_UP: 'false'
    ports:
      - '3001:3000'
    # restart: always
