version: '2'

services:
  influxdb:
    image: influxdb:1.5
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: 'true'
    volumes:
      - ./influxdb-upgrade:/var/lib/influxdb
    ports:
      - '8083:8083'
      - '8086:8086'
    restart: always
    network_mode: "bridge"
    #expose:
    # - '8083'
    # - '8086'

  grafana:
    image: grafana/grafana:5.4.2
    links:
      - influxdb
    volumes:
      - ./grafana-data:/var/lib/grafana
    environment:
      INFLUXDB_HOST: 'influxdb'
      INFLUXDB_NAME: 'tfws'
      INFLUXDB_IS_GRAFANADB: 'true'
      GF_SECURITY_ADMIN_USER: '${GF_ADMIN_USER}'
      GF_SECURITY_ADMIN_PASSWORD: '${GF_ADMIN_PASSWORD}'
      GF_USERS_ALLOW_SIGN_UP: 'false'
    ports:
      - '3001:3000'
    #expose:
      #- '3000'
    user: "104"
    network_mode: "bridge"
    restart: always
