version: '2'

services:
  influxdb:
    image: influxdb:0.13
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: 'true'
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - '8083:8083'
      - '8086:8086'
    restart: always
    network_mode: "bridge"
    #expose:
    # - '8083'
    # - '8086'

  grafana:
    image: grafana/grafana:4.2.0
    links:
      - influxdb
    volumes:
      - ./grafana-data:/var/lib/grafana
    environment:
      INFLUXDB_HOST: 'influxdb'
      INFLUXDB_NAME: 'tfws'
      INFLUXDB_IS_GRAFANADB: 'true'
      GF_SECURITY_ADMIN_USER: '${GF_ADMIN_USER}'
      GF_SECURITY_ADMIN_PASSWORD: '${GF_ADMIN_PASSWORD}'
      GF_USERS_ALLOW_SIGN_UP: 'false'
      LETSENCRYPT_HOST: '${LETSENCRYPT_HOST}'
      LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL}'
      VIRTUAL_HOST: '${VIRTUAL_HOST}'
      VIRTUAL_PORT: '${VIRTUAL_PORT}'
    #ports:
    #  - '3001:3000'
    expose:
      - '3000'
    network_mode: "bridge"
    restart: always
